spring.application.name=PBL6

# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/PBL6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.ljy.pbl6.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Redis 配置
spring.redis.host=localhost
spring.redis.port=6379

# RabbitMQ 配置
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 大模型引擎配置
mcp.model.deepseek-r1.api-url=https://api.siliconflow.cn/v1/chat/completions
mcp.model.deepseek-r1.api-key=sk-ywcsngsirfmwllhwofvbuovlslmmrlcksqmehxtztfovpfrl
mcp.model.deepseek-r1.model-name=deepseek-ai/DeepSeek-R1
